title: My personal blog
author: Javier Gallegos Barrantes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog, in this website I will show you all the works I did

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: moon
